development:
  adapter: postgresql
  encoding: unicode
  hostname: localhost
  database: nait_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  hostname: localhost
  database: nait_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  hostname: localhost
  database: nait_production
  pool: 5
